name: ChaosBand
favicon: null
layout_spectrum: 0.20974
typography_spectrum: 0.3993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0019'
    - '#060000'
    - '#300005'
    - '#c80014'
    - '#68000a'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
