name: ChaosBand
favicon: null
layout_spectrum: 0.9641981374006718
typography_spectrum: 0.34615458943881094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27097479929216206
  lightness: 0.6045701690018177
  saturation: 0.44427419314160943
  rhythmicContrast: 0.167706408072263
purpose: []
